[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit file" }
]
system = [
    { run = 'open "$@"', orphan = true, desc = "System Open" }
]
drawio = [
    { run = 'open -a "draw.io" "$@"', orphan = true, desc = "Open in draw.io" }
]

[open]
prepend_rules = [
    { url = "*.drawio", use = "drawio" },
    { mime = "{image,audio,video}/*", use = "system" },
    { mime = "application/pdf", use = "system" },
    { url = "*", use = "edit" },
]

[mgr]
show_hidden = true
