# Essentials
bind R source-file ~/.config/tmux/tmux.conf

# Better Splits (s and v)
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# Vim Pane Navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vi mode selection
bind-key -T copy-mode-vi v send-keys -X begin-selection

# disable it so yazi can use it to teleport
unbind C-t
